import "./globals.css";
import {Metadata} from "next"

export const metadata:Metadata = {
  title: {
    default:'default next js',
    template:'%s | template next.js'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="w-full bg-blue-300 p-6">
          <h1>header</h1>
        </header>
        {children}
        <footer className="w-full bg-slate-600 p-6">
          <h1>footer</h1>
        </footer>
        </body>
    </html>
  )
}
